# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vectordb.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vectordb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evectordb.proto\x12\x08vectorpp\"1\n\rInsertRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\x10\n\x08metadata\x18\x02 \x01(\t\"\x1c\n\x0eInsertResponse\x12\n\n\x02id\x18\x01 \x01(\t\"M\n\rSearchRequest\x12\x14\n\x0cquery_vector\x18\x01 \x03(\x02\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x17\n\x0f\x66ilter_metadata\x18\x03 \x01(\t\";\n\x0cSearchResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x10\n\x08metadata\x18\x03 \x01(\t\"9\n\x0eSearchResponse\x12\'\n\x07results\x18\x01 \x03(\x0b\x32\x16.vectorpp.SearchResult\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc1\x01\n\x08VectorDB\x12;\n\x06Insert\x12\x17.vectorpp.InsertRequest\x1a\x18.vectorpp.InsertResponse\x12;\n\x06Search\x12\x17.vectorpp.SearchRequest\x1a\x18.vectorpp.SearchResponse\x12;\n\x06\x44\x65lete\x12\x17.vectorpp.DeleteRequest\x1a\x18.vectorpp.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectordb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSERTREQUEST']._serialized_start=28
  _globals['_INSERTREQUEST']._serialized_end=77
  _globals['_INSERTRESPONSE']._serialized_start=79
  _globals['_INSERTRESPONSE']._serialized_end=107
  _globals['_SEARCHREQUEST']._serialized_start=109
  _globals['_SEARCHREQUEST']._serialized_end=186
  _globals['_SEARCHRESULT']._serialized_start=188
  _globals['_SEARCHRESULT']._serialized_end=247
  _globals['_SEARCHRESPONSE']._serialized_start=249
  _globals['_SEARCHRESPONSE']._serialized_end=306
  _globals['_DELETEREQUEST']._serialized_start=308
  _globals['_DELETEREQUEST']._serialized_end=335
  _globals['_DELETERESPONSE']._serialized_start=337
  _globals['_DELETERESPONSE']._serialized_end=370
  _globals['_VECTORDB']._serialized_start=373
  _globals['_VECTORDB']._serialized_end=566
# @@protoc_insertion_point(module_scope)
